[Windows]
MainStore=
LocalStore=
Username=
GroupEntryDir=
POName=

; Object Registration Section

[Objects]
Object1=FLDOBJ.DLL
Object2=MSGOBJ.DLL
Object3=ACCTOBJ.DLL
Object4=FLTOBJ.DLL
Object5=PAGEROBJ.DLL
Object6=FAXOBJ.DLL
Object7=ARTIOBJ.DLL
Object8=MCIOBJ.DLL
Object9=MHSOBJ.DLL
Object10=SERVOBJ.DLL
Object11=QOBJ.DLL
Object12=QADMIN.DLL
Object13=POADMIN.DLL
Object14=PGADMIN.DLL
Object15=QEMADMIN.DLL
Object16=LANOBJ.DLL
Object17=TXTADMIN.DLL
Object18=TXTOBJ.DLL
Object19=FAXADMIN.DLL

[personal dictionary to open]
0=personal.dic

[Main Dictionary]
Dictionary=

[View]
bNewLook=FALSE
bIconView=FALSE
bMenuBar=TRUE
bToolBar=TRUE
