; PROTOCOL.INI for LANtastic v6.0
; ------------ use with Artisoft Noderunner & AEX Adapters
; (this is a complete file, not a fragment)
;
[PROTMAN]  
  DriverName = PROTMAN$
  Dynamic = Yes


[NETBEUI_XIF]
  DriverName = netbeui$
  Sessions = 6
  NCBS = 12
  Bindings = NRODI
  LANABASE = 1


[AEXNDIS_NIF]
  DriverName = AEXNDS$


;---------------
; IOBase = 0x300
;
;
; I/O base address for AEX adapters only (not Noderunner)
;
; This parameter specifies the input/output port base address
; of the network adapter card. The specified value must match the
; setting of the network adapter card. If this parameter is not
; specified, then all valid input/output port base addresses will
; be tested to find an adapter. This parameter is required in multi-adapter
; configurations.
;
; Valid values are 0x300, 0x320, 0x340, 0x360, 0x1000, 0x2020, and 0x8020."

;---------------
; Interrupt = 15
;
; Interrupt level for AEX adapters only (not Noderunner)
;
; This parameter specifies the interrupt request level (IRQ)
; of the network adapter card. The specified value must match the
; setting of the network adapter card. On Artisoft NodeRunner Ethernet
; adapters, this parameters is not required, and is determined
; automatically. On Artisoft AE-X Ethernet adapters, if this parameter
; is not specified, a default value is used based on the I/O base
; address. Refer to your adapter documentation for a list of I/O base
; addresses and their corresponding default interrupt request levels.
;
; Valid values are 2, 3, 4, 5, 6, 7, 9, 10, and 15."
