[Windows]
MainStore=c:\lantasti\amail\
LocalStore=c:\lantasti\temp\

; Object Registration Section
[Objects]
Object1=MTASERV.DLL
Object3=MTAPAGE.DLL
Object4=MTATPAGE.DLL
Object5=MTAFAXC.DLL
Object6=MTAQMAIL.DLL
Object7=MTAQ.DLL
